### ISSUE TITLE
Запуск тестового окружения. Отсутствие pgcenter

### ISSUE THREAD

**Issue by vladislav-sidorovich** [lesovsky/postgresql-monitoring-book#8]
Работаю на mac и не пользуюсь утилитой `make`. Запускаю команды `Docker`  сам.
`docker-compose up` падает со следующей ошибкой:
```
 => ERROR [primary 2/2] RUN wget https://github.com/lesovsky/pgcenter/releases/download/v0.9.2/pgcenter_0.9.2_linux_amd64.tar.gz -o /dev/null -O - |     tar xzf - -C /usr/bin pgcenter &&       0.2s
```

Данная инструкция расположена в файле https://github.com/lesovsky/postgresql-monitoring-book/blob/c9cc2067af4ffae6daf1baee366f8d4eb3cfdee4/playground/postgres/Dockerfile

Для проверки выполняю локально  
```
curl https://github.com/lesovsky/pgcenter/releases/download/v0.9.2/pgcenter_0.9.2_linux_amd64.tar.gz -o file
```
В результате получаю пустой файл. 

Убрав эту инструкцию все остальное окружение запускается успешно.
```
#RUN wget https://github.com/lesovsky/pgcenter/releases/download/v0.9.2/pgcenter_0.9.2_linux_amd64.tar.gz -o /dev/null -O - | \
#    tar xzf - -C /usr/bin pgcenter

RUN    mkdir /var/log/postgresql && \
    chown postgres:postgres /var/log/postgresql
```

**Comment by lesovsky** [comment]
а что там за ошибка-то при выполнении wget'а?

Проверять лучше всего не curl'ом (команда кстати кривая, потому и файл пустой), а именно той командой что прописана в докерфайле. А в идеале, вообще запустить контейнер на основе образа что указан в докерфайле, шаг шагом пройтись по командам.

**Comment by vladislav-sidorovich** [comment]
проблема оказалось с моими хитрыми настройками ssl сертификатов. Для остальных думаю, что проблема неактуальна.
